name: data-sandbox
version: 0.1.0.0

library:
  source-dirs:
    - src/genetic
    - src/astar
  exposed-modules:
    - GeneticAlgorithm
    - Salesman
    - Maze
    - AStar
  dependencies:
    - base
    - array
    - random
    - containers

executables:
  data-sandbox:
    main: main.hs
    source-dirs: src
    dependencies:
      - data-sandbox
      - base
      - containers # Assuming Chart might be used later, keeping it.
      - random
